run:
  timeout: 1m

linters:
  presets:
    - bugs
    - error
    - unused
    - performance
  disable-all: true
  enable:
    - bidichk
    - durationcheck
    - err113
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nonamedreturns
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
